version: '3.8'
services:
  vllm_qwen:
    build:
      context: .
      dockerfile: Dockerfile
    image: base-vllm:latest
    command: vllm serve Qwen/Qwen2.5-1.5B-Instruct --device cuda
    ports:
      - "8001:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  vllm_nvidia:
    build:
      context: .
      dockerfile: Dockerfile
    image: base-vllm:latest
    command: vllm serve nvidia/AceInstruct-1.5B --device cuda
    ports:
      - "8002:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  vllm_huggingface:
    build:
      context: .
      dockerfile: Dockerfile
    image: base-vllm:latest
    command: vllm serve HuggingFaceTB/SmolLM2-1.7B-Instruct --device cuda
    ports:
      - "8003:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
