version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    ports:
      - "5432:5432"
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - keycloak-db

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HTTP_PORT=8181
    ports:
      - "8181:8181"
    depends_on:
      - postgres
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/realm.json
    networks:
      default:
        aliases:
          - keycloak

volumes:
  keycloak_postgres_data:

networks:
  default:
    external:
      name: iam-network
