server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/myrealm
          jwk-set-uri: http://keycloak:8181/realms/myrealm/protocol/openid-connect/certs

JWK_KID: 5e979c13-2e43-4058-bc89-f5f746ef719f